# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "sam-app"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
#resolve_s3 = true
s3_bucket = "demo-deploy-bucket-1q2w3e4r"

[default.package.parameters]
#resolve_s3 = true # if set SAM will create a new ducket for storing packged lambdas content
s3_bucket = "demo-deploy-bucket-1q2w3e4r"

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
